site_name: SLAVV MATLAB Documentation

nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        matlab:
          setup_commands: []
          paths:
            - /home/ubuntu/Vectorization-Public


