"""Management utilities for SLAVV comparison data."""

from __future__ import annotations

from ._run_layout.indexing import (
    build_experiment_index_entry,
    create_pointer_files,
    read_pointer_file,
    write_experiment_index,
    write_pointer_file,
)
from ._run_layout.inventory import (
    RunMetadata,
    analyze_checkpoints,
    cleanup_checkpoints,
    collect_directory_inventory,
    discover_run_roots,
    get_directory_size,
    get_file_inventory,
    list_runs,
    load_run_info,
    load_run_metadata,
)
from ._run_layout.managed_archive import (
    apply_managed_archive_cleanup,
    infer_experiment_slug,
    infer_target_run_name,
    is_managed_comparisons_root,
    load_artifact_cleanup,
    managed_comparisons_root_from_path,
    refresh_managed_archive_metadata,
    select_pointer_targets,
)
from ._run_layout.manifest import generate_manifest
from ._run_layout.paths import (
    classify_run_path,
    comparisons_root_from_path,
    create_experiment_path,
    is_aggregate_run_container,
    is_authoritative_managed_run_root,
    is_experiment_grouped_run_root,
    is_legacy_flat_run_root,
    is_staged_run_root,
    list_aggregate_child_runs,
    normalize_run_root_name,
    relative_run_path,
    resolve_run_layout,
    resolve_run_root,
    slugify_experiment_name,
)
from ._run_layout.status import (
    aggregate_container_rollup,
    infer_quality_gate,
    infer_run_status,
    read_run_status,
    validate_run_status_payload,
    write_run_status,
)

__all__ = [
    "RunMetadata",
    "aggregate_container_rollup",
    "analyze_checkpoints",
    "apply_managed_archive_cleanup",
    "build_experiment_index_entry",
    "classify_run_path",
    "cleanup_checkpoints",
    "collect_directory_inventory",
    "comparisons_root_from_path",
    "create_experiment_path",
    "create_pointer_files",
    "discover_run_roots",
    "generate_manifest",
    "get_directory_size",
    "get_file_inventory",
    "infer_experiment_slug",
    "infer_quality_gate",
    "infer_run_status",
    "infer_target_run_name",
    "is_aggregate_run_container",
    "is_authoritative_managed_run_root",
    "is_experiment_grouped_run_root",
    "is_legacy_flat_run_root",
    "is_managed_comparisons_root",
    "is_staged_run_root",
    "list_aggregate_child_runs",
    "list_runs",
    "load_artifact_cleanup",
    "load_run_info",
    "load_run_metadata",
    "managed_comparisons_root_from_path",
    "normalize_run_root_name",
    "read_pointer_file",
    "read_run_status",
    "refresh_managed_archive_metadata",
    "relative_run_path",
    "resolve_run_layout",
    "resolve_run_root",
    "select_pointer_targets",
    "slugify_experiment_name",
    "validate_run_status_payload",
    "write_experiment_index",
    "write_pointer_file",
    "write_run_status",
]
