"""Tests for ``dev/scripts/maintenance/refresh_matlab_mapping_appendix.py``."""

from __future__ import annotations

import importlib.util
from pathlib import Path


def _load_workspace_module(relative_path: str, module_name: str):
    repo_root = Path(__file__).resolve().parents[4]
    module_path = repo_root / relative_path
    spec = importlib.util.spec_from_file_location(module_name, module_path)
    module = importlib.util.module_from_spec(spec)
    assert spec is not None
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def test_extract_mapped_matlab_filenames_only_reads_table_entries():
    module = _load_workspace_module(
        "dev/scripts/maintenance/refresh_matlab_mapping_appendix.py",
        "refresh_matlab_mapping_appendix_extract_test",
    )
    content = """
Intro text mentions `foo.m` but this is not a table row.

| MATLAB File | Port Status | Notes |
| --- | --- | --- |
| `bar.m` | `Ported` | Something |
"""

    mapped = module._extract_mapped_matlab_filenames(content)

    assert mapped == {"bar.m"}


def test_refresh_matlab_mapping_appendix_targets_reference_mapping_doc():
    module = _load_workspace_module(
        "dev/scripts/maintenance/refresh_matlab_mapping_appendix.py",
        "refresh_matlab_mapping_appendix_path_test",
    )
    repo_root = Path(__file__).resolve().parents[4]

    assert repo_root / "docs" / "reference" / "MATLAB_MAPPING.md" == module.MATLAB_MAPPING_PATH


def test_refresh_matlab_mapping_appendix_replaces_existing_appendix(tmp_path):
    module = _load_workspace_module(
        "dev/scripts/maintenance/refresh_matlab_mapping_appendix.py",
        "refresh_matlab_mapping_appendix_main_test",
    )
    mapping_path = tmp_path / "docs" / "reference" / "MATLAB_MAPPING.md"
    matlab_dir = tmp_path / "external" / "Vectorization-Public" / "source"
    mapping_path.parent.mkdir(parents=True)
    matlab_dir.mkdir(parents=True)
    mapping_path.write_text(
        "\n".join(
            [
                "# Mapping",
                "",
                "| MATLAB File | Port Status | Notes |",
                "| --- | --- | --- |",
                "| `ported.m` | `Ported` | Already covered |",
                "",
                "## Appendix: Unmapped MATLAB Files",
                "",
                "| MATLAB File | Port Status | Notes |",
                "| --- | --- | --- |",
                "| `stale_entry.m` | `Skipped` | Stale appendix row |",
            ]
        ),
        encoding="utf-8",
    )
    (matlab_dir / "ported.m").write_text("function out = ported()\nout = 1;\n", encoding="utf-8")
    (matlab_dir / "extra_script.m").write_text("disp('hi');\n", encoding="utf-8")
    module.MATLAB_MAPPING_PATH = mapping_path
    module.MATLAB_SOURCE_DIR = matlab_dir

    module.main()

    updated = mapping_path.read_text(encoding="utf-8")
    assert "Generated by `refresh_matlab_mapping_appendix.py`" in updated
    assert "| `extra_script.m` | `Skipped` | Upstream-only or archival helper |" in updated
    assert "`stale_entry.m`" not in updated
    assert updated.count("`ported.m`") == 1
