% Headless vectorization of 180709_E_crop_M.tif using canonical 180709_E settings.
%
% Produces a new batch_* folder under workspace/scratch/matlab_crop_batches/.
% Intended for automation via:
%   matlab.exe -batch "run('scripts/matlab/vectorize_180709_E_crop_M.m')"

script_dir = fileparts(mfilename('fullpath'));
repo_root = fileparts(fileparts(script_dir));
cd(repo_root);
vectorization_root = fullfile(repo_root, 'external', 'Vectorization-Public');
addpath(genpath(vectorization_root));

crop_tif = fullfile(repo_root, 'workspace', 'datasets', ...
  '0cdf88e930482e9eb818963da22846c43b53b531582bf3aed83678b549863d06', ...
  '01_Input', '180709_E_crop_M.tif');

canonical_settings_dir = fullfile(repo_root, 'workspace', 'oracles', ...
  '180709_E_batch_190910-103039', '01_Input', 'matlab_results', ...
  'batch_190910-103039_canonical', 'settings');

out_dir = fullfile(repo_root, 'workspace', 'scratch', 'matlab_crop_batches');
if ~exist(out_dir, 'dir')
  mkdir(out_dir);
end

if ~exist(crop_tif, 'file')
  error(['Missing crop TIFF: ', crop_tif]);
end
if ~exist(canonical_settings_dir, 'dir')
  error(['Missing canonical settings dir: ', canonical_settings_dir]);
end

energy = load(fullfile(canonical_settings_dir, 'energy_190910-103039.mat'));
verts = load(fullfile(canonical_settings_dir, 'vertices_190910-103039.mat'));
edges = load(fullfile(canonical_settings_dir, 'edges_190910-103039.mat'));
netw  = load(fullfile(canonical_settings_dir, 'network_190910-103039.mat'));

name_value_pair_inputs = { ...
  'OutputDirectory', out_dir, ...
  'NewBatch', 'yes', ...
  'PreviousBatch', 'none', ...
  'PreviousWorkflow', 'none', ...
  'StartWorkflow', 'energy', ...
  'FinalWorkflow', 'network', ...
  'Visual', 'none', ...
  'SpecialOutput', 'none', ...
  'VertexCuration', 'auto', ...
  'EdgeCuration', 'auto', ...
  'Presumptive', true, ...
  ...
  'matching_kernel_string', energy.matching_kernel_string, ...
  'gaussian_to_ideal_ratio', energy.gaussian_to_ideal_ratio, ...
  'spherical_to_annular_ratio', energy.spherical_to_annular_ratio, ...
  'microns_per_voxel', energy.microns_per_voxel, ...
  'radius_of_smallest_vessel_in_microns', energy.radius_of_smallest_vessel_in_microns, ...
  'radius_of_largest_vessel_in_microns', energy.radius_of_largest_vessel_in_microns, ...
  'approximating_PSF', energy.approximating_PSF, ...
  'excitation_wavelength_in_microns', energy.excitation_wavelength_in_microns, ...
  'scales_per_octave', energy.scales_per_octave, ...
  'max_voxels_per_node_energy', energy.max_voxels_per_node_energy, ...
  'vessel_wall_thickness_in_microns', energy.vessel_wall_thickness_in_microns, ...
  ...
  'space_strel_apothem', verts.space_strel_apothem, ...
  'energy_upper_bound', verts.energy_upper_bound, ...
  'max_voxels_per_node', verts.max_voxels_per_node, ...
  'length_dilation_ratio', verts.length_dilation_ratio, ...
  ...
  'max_edge_length_per_origin_radius', edges.max_edge_length_per_origin_radius, ...
  'space_strel_apothem_edges', edges.space_strel_apothem_edges, ...
  'number_of_edges_per_vertex', edges.number_of_edges_per_vertex, ...
  ...
  'sigma_strand_smoothing', netw.sigma_strand_smoothing ...
};

disp(['Vectorizing crop TIFF: ', crop_tif]);
disp(['OutputDirectory: ', out_dir]);
time_stamp = vectorize_V200(crop_tif, name_value_pair_inputs{1, :});
disp(['Vectorization completed. time_stamp=', time_stamp]);
