
import os
import sys
import logging
from datetime import datetime
from pathlib import Path

# Ensure slavv is in path
sys.path.append(os.getcwd())

from slavv.dev.comparison import run_python_vectorization, load_parameters

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def main():
    project_root = Path(os.getcwd())
    input_file = "tests/data/slavv_test_volume.tif"
    
    # 1. Setup Directory
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    base_dir = project_root / "comparisons" / f"{timestamp}_manual_run"
    
    input_dir = base_dir / "01_Input"
    output_dir = base_dir / "02_Output"
    analysis_dir = base_dir / "03_Analysis"
    matlab_results_dir = input_dir / "matlab_results"
    
    for d in [input_dir, output_dir, analysis_dir, matlab_results_dir]:
        os.makedirs(d, exist_ok=True)
        
    logging.info(f"Created run directory: {base_dir}")
    
    # 2. Generate MATLAB script for user
    matlab_script_content = f"""
% Manual MATLAB Vectorization Script
% Generated by SLAVV Assistant

% Setup paths
repo_root = '{str(project_root).replace(os.sep, '/')}';
addpath(fullfile(repo_root, 'scripts'));
addpath(fullfile(repo_root, 'external', 'Vectorization-Public'));

% Input/Output
input_file = '{str(project_root / input_file).replace(os.sep, '/')}';
output_dir = '{str(matlab_results_dir).replace(os.sep, '/')}';

disp('Starting Vectorization...');
try
    run_matlab_vectorization(input_file, output_dir);
    disp('Success! Results saved to:');
    disp(output_dir);
catch e
    disp('Error running vectorization:');
    disp(e.message);
end
"""
    
    matlab_script_path = base_dir / "run_this_in_matlab.m"
    with open(matlab_script_path, "w") as f:
        f.write(matlab_script_content)
        
    logging.info(f"Generated MATLAB script: {matlab_script_path}")
    
    # 3. Run Python Vectorization
    logging.info("Running Python Vectorization...")
    params = load_parameters()
    python_output_dir = output_dir / "python_results"
    os.makedirs(python_output_dir, exist_ok=True)
    
    python_results = run_python_vectorization(input_file, str(python_output_dir), params)
    
    if python_results.get('success'):
        logging.info("Python vectorization complete.")
    else:
        logging.error("Python vectorization failed.")

    logging.info("\n" + "="*50)
    logging.info("NEXT STEPS:")
    logging.info(f"1. Open MATLAB and run the script: {matlab_script_path}")
    logging.info("2. Once MATLAB finishes, tell me: 'MATLAB is done, please run comparison'")
    logging.info("="*50)

if __name__ == "__main__":
    main()
