% Parameterized headless vectorization for one synthetic complexity-ladder rung.
% Invoked by scripts/run_synthetic_complexity_ladder.py via:
%   matlab.exe -batch "run('<driver>'); vectorize_ladder_rung('<tif>','<out_dir>')"
%
% The function lives in this file; run() loads it, then the batch calls it.

function vectorize_ladder_rung(tif_path, out_dir)
  if nargin < 2
    error('vectorize_ladder_rung requires tif_path and out_dir');
  end

  script_dir = fileparts(mfilename('fullpath'));
  % scripts/ -> repo root
  repo_root = fileparts(script_dir);
  cd(repo_root);

  vectorization_root = fullfile(repo_root, 'external', 'Vectorization-Public');
  addpath(genpath(vectorization_root));

  if ~exist(out_dir, 'dir')
    mkdir(out_dir);
  end
  if ~exist(tif_path, 'file')
    error(['Missing synthetic TIFF: ', tif_path]);
  end

  name_value_pair_inputs = { ...
    'OutputDirectory', out_dir, ...
    'NewBatch', 'yes', ...
    'PreviousBatch', 'none', ...
    'PreviousWorkflow', 'none', ...
    'StartWorkflow', 'energy', ...
    'FinalWorkflow', 'network', ...
    'Visual', 'none', ...
    'SpecialOutput', 'none', ...
    'VertexCuration', 'auto', ...
    'EdgeCuration', 'auto', ...
    'Presumptive', true, ...
    ...
    'microns_per_voxel', [1.0, 1.0, 1.0], ...
    'radius_of_smallest_vessel_in_microns', 1.5, ...
    'radius_of_largest_vessel_in_microns', 5.0, ...
    'approximating_PSF', false, ...
    'scales_per_octave', 1.0, ...
    'gaussian_to_ideal_ratio', 1.0, ...
    'spherical_to_annular_ratio', 1.0, ...
    'max_voxels_per_node_energy', 1e5, ...
    ...
    'space_strel_apothem', 1, ...
    'energy_upper_bound', 0, ...
    'max_voxels_per_node', 6000, ...
    'length_dilation_ratio', 1.0, ...
    ...
    'max_edge_length_per_origin_radius', 30, ...
    'space_strel_apothem_edges', 1, ...
    'number_of_edges_per_vertex', 4, ...
    ...
    'sigma_strand_smoothing', 1 ...
  };

  disp(['Vectorizing ladder TIFF: ', tif_path]);
  disp(['OutputDirectory: ', out_dir]);
  tic;
  time_stamp = vectorize_V200(tif_path, name_value_pair_inputs{1, :});
  elapsed = toc;
  disp(['Vectorization completed. time_stamp=', time_stamp]);
  disp(['MATLAB_ELAPSED_SEC=', num2str(elapsed, '%.3f')]);

  timing_path = fullfile(out_dir, 'matlab_timing.txt');
  fid = fopen(timing_path, 'w');
  fprintf(fid, 'time_stamp=%s\n', time_stamp);
  fprintf(fid, 'elapsed_sec=%.6f\n', elapsed);
  fclose(fid);
end
