% Launch the original MATLAB Vertex Curator on a preserved synthetic sample.
%
% This script is intentionally interactive. It opens the unmodified
% Vectorization-Public vertex_curator against the y_junction_32 MATLAB
% artifacts and writes any saved curation only under workspace/scratch.

script_path = mfilename('fullpath');
repo_root = fileparts(fileparts(fileparts(script_path)));
source_root = fullfile(repo_root, 'external', 'Vectorization-Public', 'source');
sample_batch = fullfile( ...
    repo_root, ...
    'workspace', 'experiments', 'synthetic_complexity_ladder', ...
    'y_junction_32', 'matlab_batches', 'batch_260814-191343');

vertices_path = fullfile( ...
    sample_batch, 'vectors', 'vertices_260814-191343_y_junction_32.mat');
energy_settings_path = fullfile( ...
    sample_batch, 'settings', 'energy_260814-191343.mat');
vertex_settings_path = fullfile( ...
    sample_batch, 'settings', 'vertices_260814-191343.mat');
energy_metadata_path = fullfile( ...
    sample_batch, 'data', 'energy_260814-191343_y_junction_32.mat');
original_path = fullfile( ...
    sample_batch, 'data', 'original_y_junction_32');
energy_path = fullfile( ...
    sample_batch, 'data', 'energy_260814-191343_y_junction_32');

required_paths = { ...
    source_root, vertices_path, energy_settings_path, vertex_settings_path, ...
    energy_metadata_path, original_path, energy_path};
for path_index = 1:numel(required_paths)
    if ~exist(required_paths{path_index}, 'file') && ...
            ~exist(required_paths{path_index}, 'dir')
        error('SLAVV:MissingSampleArtifact', ...
            'Required sample artifact is missing: %s', required_paths{path_index});
    end
end

addpath(source_root);

vertices = load(vertices_path);
energy_settings = load(energy_settings_path);
vertex_settings = load(vertex_settings_path);
energy_metadata = load(energy_metadata_path);

% The legacy curator expects these exact vector orientations.
microns_per_pixel = reshape(energy_settings.microns_per_voxel, 1, 3);
lumen_radius_in_microns_range = reshape( ...
    energy_settings.lumen_radius_in_microns_range, [], 1);
display_radii = ...
    vertex_settings.length_dilation_ratio * lumen_radius_in_microns_range;

scratch_dir = fullfile(repo_root, 'workspace', 'scratch', 'manual_curation_showcase');
if ~exist(scratch_dir, 'dir')
    mkdir(scratch_dir);
end
curation_name = [ ...
    'curated_vertices_', datestr(now, 'yymmdd-HHMMSS'), '_y_junction_32'];
curation_path = fullfile(scratch_dir, curation_name);

fprintf('\nOpening the original SLAVV MATLAB Vertex Curator.\n');
fprintf('Sample: y_junction_32\n');
fprintf('Any saved edits go to: %s.mat\n\n', curation_path);

vertex_curator( ...
    vertices.vertex_energies, ...
    vertices.vertex_space_subscripts, ...
    vertices.vertex_scale_subscripts, ...
    display_radii, ...
    microns_per_pixel, ...
    original_path, ...
    curation_path, ...
    energy_path, ...
    energy_metadata.intensity_limits, ...
    [min(vertices.vertex_energies), 0]);
