
% Manual MATLAB Vectorization Script
% Generated by SLAVV Assistant

% Setup paths
repo_root = 'C:/Users/alw4834/OneDrive - The University of Texas at Austin/Documents 1/GitHub/slavv2python';
addpath(fullfile(repo_root, 'scripts'));
addpath(fullfile(repo_root, 'external', 'Vectorization-Public'));

% Input/Output
input_file = 'C:/Users/alw4834/OneDrive - The University of Texas at Austin/Documents 1/GitHub/slavv2python/tests/data/slavv_test_volume.tif';
output_dir = 'C:/Users/alw4834/OneDrive - The University of Texas at Austin/Documents 1/GitHub/slavv2python/comparisons/20260210_101213_manual_run/01_Input/matlab_results';

disp('Starting Vectorization...');
try
    run_matlab_vectorization(input_file, output_dir);
    disp('Success! Results saved to:');
    disp(output_dir);
catch e
    disp('Error running vectorization:');
    disp(e.message);
end
