name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy scipy scikit-image tifffile pandas scikit-learn joblib plotly streamlit pytest
      - name: Run checks
        run: |
          python -m py_compile $(git ls-files '*.py')
          pytest -q
